---
name: "🐞 Bug Report"
description: Create a report to help us fix issues.
labels: ["issue: bug", "status: pending"]
body:
- type: markdown
  attributes:
    value: |
      **Thank you for using MKS WiFi Plugin and for reporting a bug.**
      
      Before filing, please check if the issue already exists (either open or closed) by using the search bar on the issues page. If it does, comment there. Even if it's closed, we can reopen it based on your comment. 
      
      Also, please note the plugin version in the title of the issue (for example "[1.2.4] It doesn't work well with Cura 4.11.0"). Please do not write things like **Request** or **BUG** in the title, this is what labels are for.
- type: input
  attributes:
    label: Plugin Version
    description: The version of MKS WiFi Plugin this issue occurs with.
    placeholder: "1.4.0"
  validations:
    required: true
- type: input
  attributes:
    label: Cura Version
    description: The version of Cura this issue occurs with.
    placeholder: "5.0"
  validations:
    required: true
- type: input
  attributes:
    label: Platform
    description: Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.
    placeholder: "Windows 10"
  validations:
    required: true
- type: input
  attributes:
    label: Printer
    description: Which printer was selected in Cura?
    placeholder: "Flying Beer Ghost 5"
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction steps
    description: Tell us what you did!
    placeholder: |
      1. Something you did
      2. Something you did next
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual results
    description: What happens after the above steps have been followed.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected results
    description: What should happen after the above steps have been followed.
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      Please be sure to add the following files:
        * **Screenshots** of showing the problem, perhaps before/after images.
        * A **log file** for crashes and similar issues.
          You can find your log file here:
          Windows: `%APPDATA%\cura\<Cura version>\cura.log` or usually `C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
          MacOS: `$USER/Library/Application Support/cura/<Cura version>/cura.log`
          Ubuntu/Linus: `$USER/.local/share/cura/<Cura version>/cura.log` 
          
          If the Cura user interface still starts, you can also reach this directory from the application menu in Help -> Show settings folder 
- type: checkboxes
  attributes:
    label: Checklist of files to include
    options:
      - label: Log file
- type: textarea
  attributes:
    label: Additional information & file uploads  
    description: You can add these files and additional information that is relevant to the issue in the comments below.
  validations:
    required: true

---

<!--📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛

Oh, hi there! 😄

To expedite issue processing, please search open and closed issues before submitting a new one.
Please read our Rules of Conduct at this repository's `.github/CODE_OF_CONDUCT.md`

📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛-->