---
name: "📚 Documentation"
labels: ["issue: documentation", "status: pending"]
description: 'Let us know if any documentation is missing or could be improved'

body:
- type: markdown
  attributes:
    value: |
      **Thank you for using MKS WiFi Plugin and wanting to improve our documentation**
      
      Before filing, please check if the question already exists (either open or closed) by using the search bar on the issues page. If it does, comment there. Even if it's closed, we can reopen it based on your comment. 
      
      Please do not write things like **Request** or **BUG** in the title, this is what labels are for.
- type: textarea
  attributes:
    label: Describe your use-case which is not covered by existing documentation.
    description: If it is easier to submit a documentation patch instead of writing an issue, just do it!
  validations:
    required: true

- type: textarea
  attributes:
    label: Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

- type: textarea
  attributes:
    label: Are you interested in contributing to the documentation?
    description: Indicate if this is something you would like to work on, and how we can best support you in doing so. More details [on contributing](https://github.com/PrintMakerLab/.github/blob/main/CONTRIBUTING.md)

---

<!--📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛

Oh, hi there! 😄

To expedite issue processing, please search open and closed issues before submitting a new one.
Please read our Rules of Conduct at this repository's `.github/CODE_OF_CONDUCT.md`

📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛-->