name: Question
description: Ask a question related to this project.
labels: "question"
body:
- type: markdown
  attributes:
    value: |
      **Thank you for using MKS WiFi Plugin and wanting to ask a question.**
      
      Before filing, please check if the question already exists (either open or closed) by using the search bar on the issues page. If it does, comment there. Even if it's closed, we can reopen it based on your comment. 
      
      Please do not write things like **Request** or **BUG** in the title, this is what labels are for.
- type: textarea
  attributes:
    label: What is your question?
    description: Please describe a clear and concise description of what the question is.
    placeholder: Can you answer me...
  validations:
    required: true