name: "Cura-plugin-package release"

on:
  push:
    tags:
      - "*.*.*"

jobs:
  create-curapackages:
    name: "New Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          path: "build"

      - name: Set release version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF##*/}

      - name: "Build"
        uses: PrintMakerLab/cura-make-plugin-package@main
        with:
          source_folder: "build"
          package_info_path: "build/.github/workflows/package.json"

      - name: "Upload release binary"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          cd build
          files="$(find ../ -type f -name "*.curapackage" -printf "-a %p ")"
          gh release edit $files -m "" "$RELEASE_VERSION"

      