name: "Update i18n"

on:
  push:
    branches-ignore:
      - develop
      - 'release-**'

jobs:
  update-i18n:
    name: "Update i18n"
    runs-on: "ubuntu-latest"

    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: gettext
      - uses: actions/checkout@v3

      - name: Ensure i18n folder exists
        run: mkdir -p i18n

      - name: Hash current pot messages
        id: hash_before
        run: echo "##[set-output name=i18n_hash;]$(grep '^msgid' i18n/*.pot | sort | sha1sum)"

      - name: Update .pot from Python files
        run: xgettext --package-name='MKS WiFi Plugin' -o i18n/mksplugin.pot                 --language=python     --from-code=UTF-8 -ki18n:1 -ki18nc:1c,2 -ki18np:1,2 -ki18ncp:1c,2,3 $(find -L . -name \*.py)
      - name: Update .pot from QML files
        run: xgettext --package-name='MKS WiFi Plugin' -o i18n/mksplugin.pot --join-existing --language=javascript --from-code=UTF-8 -ki18n:1 -ki18nc:1c,2 -ki18np:1,2 -ki18ncp:1c,2,3 $(find -L . -name \*.qml)

      - name: Hash new pot messages
        id: hash_after
        run: echo "##[set-output name=i18n_hash;]$(grep '^msgid' i18n/*.pot | sort | sha1sum)"

      - if: ${{steps.hash_after.outputs.i18n_hash != steps.hash_before.outputs.i18n_hash}}
        name: Update .po files
        run: find i18n -name mksplugin.po -exec msgmerge --update {} --backup=none i18n/mksplugin.pot \;

      - if: ${{steps.hash_after.outputs.i18n_hash != steps.hash_before.outputs.i18n_hash}}
        name: Ensure LC_MESSAGES folder exists
        run: find i18n -maxdepth 1 -name '*_*' -exec mkdir -p {}/LC_MESSAGES \;

      - if: ${{steps.hash_after.outputs.i18n_hash != steps.hash_before.outputs.i18n_hash}}
        name: Update .mo files
        run: find i18n -maxdepth 1 -name '*_*' -exec msgfmt {}/mksplugin.po -o {}/LC_MESSAGES/mksplugin.mo \;

      - if: ${{steps.hash_after.outputs.i18n_hash != steps.hash_before.outputs.i18n_hash}}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: .pot .po .mo updated