name: Project Automation / Pull Request
on:
  pull_request_target:
    types: [opened, reopened]
  workflow_call:
    secrets:
      ADD_TO_PROJECT_PAT:
        required: true

env:
  KANBAN_PROJECT_URL: https://github.com/orgs/PrintMakerLab/projects/3

jobs:
  add-to-kanban-project:
    name: Add all pull requests to the Kanban project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ env.KANBAN_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}